[build]
  command = "npm run build"
  publish = "dist" # Agar `vite` ishlatayotgan bo‘lsang
  # Agar `create-react-app` ishlatayotgan bo‘lsang:
  # publish = "build"

[dev]
  command = "npm run dev"
  port = 3000
  targetPort = 5173 # Vite default port
  framework = "vite" # Agar CRA bo‘lsa, yozma

[redirects]
  [[redirects]]
    from = "/*"
    to = "/index.html"
    status = 200